spring:
  datasource:
    url: jdbc:mysql://localhost/event_producer_demo?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: hapcloud
    password: handhand
    initialize: true
    schema: classpath:import.sql
  eureka:
    client:
      serviceUrl:
        defaultZone: http://localhost:8000/eureka
security:
  basic:
    enabled: false

