server:
  port: 8768
  tomcat:
      max-threads: 600
      max-connections: 600
spring:
   application:
     name:  consumer-feign-service
   datasource:
     url: jdbc:mysql://localhost/hap_event_service?useUnicode=true&characterEncoding=utf-8&useSSL=false
     username: hapcloud
     password: handhand
   quartz:
     job-store-type: jdbc
