# application.yml
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/apim_service?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: choerodon
    password: 123456
  cloud:
    gateway:
      enabled: true
      routes:
        - id: global
          uri: http://localhost
          predicates:
            - Path=/**
  redis:
    port: 6379
    host: localhost
    database: 5
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 20000

ribbon:
  ReadTimeout: 5000
  ConnectTimeout: 5000
mybatis:
  mapperLocations: classpath*:/mapper/*.xml
  configuration: # 数据库下划线转驼峰配置
    mapUnderscoreToCamelCase: true
management:
  endpoints:
    web:
      exposure:
        include: '*'
apim:
  request-record:
    enabled: true
    ring-buffer-size: 2048
  filter:
    enabled: true
    setting:
      AdaptCachedBodyGlobalFilter: false
      ApiRateLimitFilter: true
      ForwardPathFilter: false
      WebsocketRoutingFilter: true
      LoadBalancerClientFilter: false
      HystrixCircuitBreakerFilter: true
      IpRateLimitFilter: true
      SubscribeRateLimitFilter: true
logging:
  level:
    io:
      choerodon:
        mybatis:
          helper:
            AuditHelper: error