spring:
  datasource:
    url: jdbc:mysql://localhost/hap_user_service?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root
  redis:
    host: localhost
    port: 6379
  rabbitmq:
    host: localhost
    port: 5672
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 3000
zuul:
  addHostHeader: true
  ratelimit:
    # 根据自己的需求进行配置
    enabled: false # 限流器开关
    policies: # 策略集
      fws: # 服务别名，需与zuul.routes.路由名对应
        default-user-policy: # 该服务的默认策略
          limit: 100000000 # 单位时间的访问次数上限
          refresh-interval: 1 # 访问次数刷新时间周期
        user-policies: # 该服务针对特定用户设定的限流策略
          admin: # 用户名
            limit: 100000000 # 该服务针对该用户的单位时间访问次数上限
            refresh-interval: 1 # 该服务针对该用户的访问次数刷新的时间周期
  routes:
    uaa:
      path: /uaa/**
      serviceId: hap-user-service
    fws:
      path: /fws/**
      serviceId: hap-framework-service
    admin:
      path: /admin/**
      serviceId: hap-user-admin-service
    oauth:
      path: /oauth/**
      sensitiveHeaders:
      serviceId: hap-oauth-server
      stripPrefix: false
    dev:
      path: /dev/**
      serviceId: hap-dome-service
    aab:
      path: /aab/**
      serviceId: client-server-a
  semaphore:
    max-semaphores: 300
security:
  oauth2:
    resource:
      userInfoUri: http://hap-oauth-server/oauth/api/user
  ignored:
    - /oauth/**
    - /**/skip/**
swagger:
  oauthUrl: http://localhost:8080/oauth/oauth/authorize
logging:
  level:
   com:
    hand:
      hap:
        cloud:
          gateway:
            ws: debug