eureka:
  instance:
    preferIpAddress: true
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 3
  client:
    serviceUrl:
      defaultZone: ${EUREKA_DEFAULT_ZONE:http://localhost:8000/eureka/}
security:
  basic:
    enabled: false
  ignored: /swagger-ui.html,/swagger-resources/**, /webjars/** , /docs/**