---
spring:
  profiles: dev
eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8000/eureka/

---
spring:
  profiles: site
eureka:
  instance:
    hostname: me.jcala
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8000/eureka/