spring:
  datasource:
    url: jdbc:mysql://localhost/event_consumer_demo?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: hapcloud
    password: handhand
    initialize: true
    schema: classpath:import.sql
  eureka:
    client:
      serviceUrl:
        defaultZone: http://localhost:8000/eureka
security:
  basic:
    enabled: false
choerodon:
 event:
   consumer:
     enabled: true # 是否开启，不设置默认开启
     queue-type: kafka # 消息队列类型
     enable-duplicate-remove: true # 是否开启去重
     failed-strategy: nothing # 失败策略。支持nothing(什么都不做), send_back_event_store(回传到event store)两种
     retry:
       enabled: true # 是否开启重试功能
     kafka:
       bootstrap-servers: localhost:9092
logging:
  level:
    io.choerodon.event.consumer: debug
    io.choerodon.mybatis: debug
    me.jcala.eureka.event.consumer.mapper: debug
