server:
    port: 8770
spring:
  application:
    name: mybatis-page
  datasource:
    initialize: true
    url: jdbc:mysql://localhost/mybatis_test?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root
    schema: classpath:import.sql
logging:
  level:
    com.ibatis: debug
    me.flyleft.mybatis.page.mapper: debug
    com.ibatis.common.jdbc.SimpleDataSource: debug
    com.ibatis.common.jdbc.ScriptRunner: debug
    com.ibatis.sqlmap.engine.impl.SqlMapClientDelegate: debug
    java.sql.Connection: debug
    java.sql.Statement: debug
    java.sql.PreparedStatement: debug
security:
  basic:
    enabled: false
